set (VictronVenusOS_QML_MODULE_SINGLETON_SOURCES # All qml singletons have to be added here
    components/CommonWords.qml
    components/FirmwareVersion.qml
    Global.qml
)
set_source_files_properties(${VictronVenusOS_QML_MODULE_SINGLETON_SOURCES} PROPERTIES QT_QML_SINGLETON_TYPE TRUE)

# VENUS_QML_MODULE
set (VictronVenusOS_QML_MODULE_SOURCES
    ${VictronVenusOS_QML_MODULE_SINGLETON_SOURCES}

    ApplicationContent.qml
    FrameRateVisualizer.qml

    components/AcceptButtonBackground.qml
    components/AcPhasesCurrentRange.qml
    components/AcInputDirectionIcon.qml
    components/AcOutput.qml
    components/AcPhase.qml
    components/Arc.qml
    components/ArcGauge.qml
    components/ArcGaugeQuantityRow.qml
    components/AsymmetricRoundedRectangle.qml
    components/BarGauge.qml
    components/BarGaugeBase.qml
    components/BaseListView.qml
    components/Breadcrumbs.qml
    components/BriefSidePanelWidget.qml
    components/BriefCenterDisplay.qml
    components/CardViewLoader.qml
    components/CircularMultiGauge.qml
    components/CircularSingleGauge.qml
    components/CheapBarGauge.qml
    components/ClippingBarGauge.qml
    components/ColorPresetGrid.qml
    components/ColorSelector.qml
    components/ColorWheelModeButton.qml
    components/ControlCard.qml
    components/CpuMonitor.qml
    components/DateSelector.qml
    components/DeviceListDelegate.qml
    components/DeviceListPluginPage.qml
    components/DevicePage.qml
    components/DynamicValueRange.qml
    components/ElectricalQuantityLabel.qml
    components/EnvironmentGauge.qml
    components/EnvironmentGaugePanel.qml
    components/ExpandedTanksView.qml
    components/FirmwareUpdate.qml
    components/FittedQuantityLabel.qml
    components/FixedWidthLabel.qml
    components/GaugeModel.qml
    components/GaugeHeader.qml
    components/GeneratorManualControlButton.qml
    components/GensetStartStop1Finder.qml
    components/FlatListItemSeparator.qml
    components/GeneratorIconLabel.qml
    components/GradientListView.qml
    components/GsmStatusIcon.qml
    components/IconButton.qml
    components/InputPanel.qml
    components/InverterAcOutSettings.qml
    components/Led.qml
    components/LoadGraph.qml
    components/LoadGraphShapePath.qml
    components/KeyNavigationListHelper.qml
    components/MultiStepButton.qml
    components/NavBar.qml
    components/NavButton.qml
    components/NetworkServices.qml
    components/NotificationCounter.qml
    components/NotificationDelegate.qml
    components/ObjectAcConnection.qml
    components/ObjectModelMonitor.qml
    components/Page.qml
    components/PageGensetModel.qml
    components/PageStack.qml
    components/VeQuickItemsQuotient.qml
    components/ProgressArc.qml
    components/QuantityGroupListHeader.qml
    components/QuantityLabel.qml
    components/QuantityRow.qml
    components/QuantityTable.qml
    components/QuantityTableMetrics.qml
    components/QuantityTableSummary.qml
    components/RadioButtonListPage.qml
    components/RsSystemAcIODisplay.qml
    components/SegmentedButtonRow.qml
    components/SeparatorBar.qml
    components/SettingsColumn.qml
    components/SettingsRangeSlider.qml
    components/SettingsSlider.qml
    components/SettingSync.qml
    components/ShinyProgressArc.qml
    components/SideGauge.qml
    components/SideMultiGauge.qml
    components/SolarDetailBox.qml
    components/SolarHistoryChart.qml
    components/SolarHistoryErrorView.qml
    components/SolarHistoryTableView.qml
    components/SolarYieldGauge.qml
    components/SolarYieldGraph.qml
    components/SplashView.qml
    components/SpinBoxDecimalConverter.qml
    components/StatusBar.qml
    components/SwipePageModel.qml
    components/SwipeViewPage.qml
    components/SystemBatteryDelegate.qml
    components/SystemBatteryDeviceModel.qml
    components/SystemReason.qml
    components/TabBar.qml
    components/TankItem.qml
    components/TankGauge.qml
    components/TemperatureRelaySettings.qml
    components/ThreePhaseBarGauge.qml
    components/ThreePhaseDisplay.qml
    components/ThreePhaseIOTable.qml
    components/ThreePhaseQuantityTable.qml
    components/TimeSelector.qml
    components/ToastNotification.qml
    components/Utils.js
    components/ValueRange.qml
    components/VeBusAcIODisplay.qml
    components/ViewGradient.qml
    components/WasmVirtualKeyboardHandler.qml
    components/WifiModel.qml
    components/ClassAndVrmInstance.qml
    components/controls/AutoToggleButton.qml
    components/controls/Button.qml
    components/controls/CloseButton.qml
    components/controls/ComboBox.qml
    components/controls/EditFrame.qml
    components/controls/GlobalKeyNavigationHighlight.qml
    components/controls/Label.qml
    components/controls/ListItemButton.qml
    components/controls/ListPressArea.qml
    components/controls/MiniSlider.qml
    components/controls/MiniSpinBox.qml
    components/controls/MiniToggleButton.qml
    components/controls/MomentaryButton.qml
    components/controls/PressArea.qml
    components/controls/PressEffect.qml
    components/controls/ProgressBar.qml
    components/controls/RadioButton.qml
    components/controls/RangeSlider.qml
    components/controls/RemoveButton.qml
    components/controls/ScrollBar.qml
    components/controls/Slider.qml
    components/controls/SliderIndicator.qml
    components/controls/SpinBox.qml
    components/controls/SpinBoxInputArea.qml
    components/controls/SwipeView.qml
    components/controls/Switch.qml
    components/controls/TemperatureSlider.qml
    components/controls/TextField.qml
    components/controls/ToggleButtonRow.qml

    components/dialogs/ColorWheelDialog.qml
    components/dialogs/CurrentLimitDialog.qml
    components/dialogs/DateSelectorDialog.qml
    components/dialogs/DialogShadow.qml
    components/dialogs/VrmInstanceSwapDialog.qml
    components/dialogs/ESSMinimumSOCDialog.qml
    components/dialogs/EvcsChargerModeDialog.qml
    components/dialogs/GeneratorDialog.qml
    components/dialogs/GeneratorStartDialog.qml
    components/dialogs/GeneratorStopDialog.qml
    components/dialogs/GeneratorDisableAutoStartDialog.qml
    components/dialogs/InverterChargerModeDialog.qml
    components/dialogs/InverterChargerEssModeDialog.qml
    components/dialogs/ModalDialog.qml
    components/dialogs/ModalRebootingDialog.qml
    components/dialogs/ModalWarningDialog.qml
    components/dialogs/NumberSelectorDialog.qml
    components/dialogs/SecurityProfilePasswordDialog.qml
    components/dialogs/SolarDailyHistoryDialog.qml
    components/dialogs/TimeSelectorDialog.qml

    components/listitems/ListAcInError.qml
    components/listitems/ListActiveAcInput.qml
    components/listitems/ListAlarmLevelRadioButtonGroup.qml
    components/listitems/ListAlarmState.qml
    components/listitems/ListBriefCenterDetails.qml
    components/listitems/ListChargeSchedule.qml
    components/listitems/ListClearHistoryButton.qml
    components/listitems/ListCurrentLimitButton.qml
    components/listitems/ListDcInputQuantityGroup.qml
    components/listitems/ListDcOutputQuantityGroup.qml
    components/listitems/ListEvcsSetCurrentSpinBox.qml
    components/listitems/ListFirmwareCheckButton.qml
    components/listitems/ListFirmwareImageTypeInstalled.qml
    components/listitems/ListFirmwareVersion.qml
    components/listitems/ListGeneratorError.qml
    components/listitems/ListInverterChargerModeButton.qml
    components/listitems/ListLink.qml
    components/listitems/ListMqttAccessSwitch.qml
    components/listitems/ListMountStateButton.qml
    components/listitems/ListAcInPositionRadioButtonGroup.qml
    components/listitems/ListOutputBatteryRadioButtonGroup.qml
    components/listitems/ListPvInverterPositionRadioButtonGroup.qml
    components/listitems/ListRebootButton.qml
    components/listitems/ListRelayState.qml
    components/listitems/ListResetHistory.qml
    components/listitems/ListTemperatureRelay.qml
    components/listitems/ListVolumeUnitRadioButtonGroup.qml

    components/listitems/core/BaseListItem.qml
    components/listitems/core/BaseListLoader.qml
    components/listitems/core/ListAlarm.qml
    components/listitems/core/ListButton.qml
    components/listitems/core/ListDateSelector.qml
    components/listitems/core/ListIntField.qml
    components/listitems/core/ListIpAddressField.qml
    components/listitems/core/ListItem.qml
    components/listitems/core/ListItemBackground.qml
    components/listitems/core/ListNavigation.qml
    components/listitems/core/ListPortField.qml
    components/listitems/core/ListQuantityField.qml
    components/listitems/core/ListQuantityGroup.qml
    components/listitems/core/ListQuantityGroupNavigation.qml
    components/listitems/core/ListQuantity.qml
    components/listitems/core/ListRadioButton.qml
    components/listitems/core/ListRadioButtonGroup.qml
    components/listitems/core/ListRangeSlider.qml
    components/listitems/core/ListSlider.qml
    components/listitems/core/ListSpinBox.qml
    components/listitems/core/ListSwitch.qml
    components/listitems/core/ListSwitchForced.qml
    components/listitems/core/ListTemperature.qml
    components/listitems/core/ListText.qml
    components/listitems/core/ListTextField.qml
    components/listitems/core/ListTimeSelector.qml
    components/listitems/core/PrimaryListLabel.qml
    components/listitems/core/SecondaryListLabel.qml
    components/listitems/core/SectionHeader.qml
    components/listitems/core/SettingsListHeader.qml
    components/listitems/core/SettingsListNavigation.qml
    components/listitems/core/SliderHandleHighlight.qml

    components/switches/SwitchableOutputCardDelegateHeader.qml
    components/switches/SwitchableOutputGroupCard.qml
    components/switches/SwitchableOutputDimmableSlider.qml
    components/switches/SwitchableOutputSlider.qml
    components/switches/delegates/SwitchableOutputCardDelegate_0.qml
    components/switches/delegates/SwitchableOutputCardDelegate_1.qml
    components/switches/delegates/SwitchableOutputCardDelegate_2.qml
    components/switches/delegates/SwitchableOutputCardDelegate_3.qml
    components/switches/delegates/SwitchableOutputCardDelegate_4.qml
    components/switches/delegates/SwitchableOutputCardDelegate_6.qml
    components/switches/delegates/SwitchableOutputCardDelegate_7.qml
    components/switches/delegates/SwitchableOutputCardDelegate_8.qml
    components/switches/delegates/SwitchableOutputCardDelegate_9.qml
    components/switches/delegates/SwitchableOutputCardDelegate_10.qml
    components/switches/delegates/SwitchableOutputCardDelegate_color.qml

    components/widgets/AcWidget.qml
    components/widgets/AcInputWidget.qml
    components/widgets/AcLoadsWidget.qml
    components/widgets/BatteryWidget.qml
    components/widgets/DcInputWidget.qml
    components/widgets/DcLoadsWidget.qml
    components/widgets/EssentialLoadsWidget.qml
    components/widgets/EvcsWidget.qml
    components/widgets/InverterChargerWidget.qml
    components/widgets/OverviewWidget.qml
    components/widgets/SolarYieldWidget.qml
    components/widgets/WidgetConnector.qml
    components/widgets/WidgetConnectorAnchor.qml
    components/widgets/WidgetConnectorPath.qml
    components/widgets/WidgetHeader.qml

    data/AcInputs.qml
    data/DataManager.qml
    data/DcInputs.qml
    data/EnvironmentInputs.qml
    data/Ess.qml
    data/EvChargers.qml
    data/Generators.qml
    data/InverterChargers.qml
    data/Notifications.qml
    data/SolarInputs.qml
    data/StartPageConfiguration.qml
    data/Switches.qml
    data/System.qml
    data/SystemLoad.qml
    data/SystemSettings.qml
    data/Tanks.qml
    data/VenusPlatform.qml

    data/common/AcData.qml
    data/common/AcInputSettings.qml
    data/common/AcInputSettingsModel.qml
    data/common/AcInputSystemInfo.qml
    data/common/AcInput.qml
    data/common/ActiveSystemBattery.qml
    data/common/DcDevice.qml
    data/common/DeviceModel.qml
    data/common/EvCharger.qml
    data/common/Generator.qml
    data/common/GensetErrorModel.qml
    data/common/Inverter.qml
    data/common/PvInverter.qml
    data/common/PvMonitor.qml
    data/common/SolarDailyHistory.qml
    data/common/SolarDevice.qml
    data/common/SolarHistory.qml
    data/common/SolarHistoryErrorModel.qml
    data/common/SolarTracker.qml
    data/common/SolarTrackerDailyHistory.qml
    data/common/Tank.qml
    data/common/TankDescription.qml
    data/common/TankModel.qml

    pages/AuxCardsPage.qml
    pages/BriefSidePanel.qml
    pages/BriefPage.qml
    pages/ControlCardsPage.qml
    pages/DialogLayer.qml
    pages/EnvironmentTab.qml
    pages/LevelsPage.qml
    pages/LevelsTab.qml
    pages/MainView.qml
    pages/NotificationLayer.qml
    pages/NotificationsPage.qml
    pages/OverviewPage.qml
    pages/PageManager.qml
    pages/SettingsPage.qml
    pages/TanksTab.qml
    pages/controlcards/ESSCard.qml
    pages/controlcards/EVCSCard.qml
    pages/controlcards/GeneratorCard.qml
    pages/controlcards/InverterChargerCard.qml
    pages/evcs/EvChargerListPage.qml
    pages/evcs/EvChargerPage.qml
    pages/evcs/EvChargerSetupPage.qml
    pages/invertercharger/InverterChargerListPage.qml
    pages/invertercharger/OverviewInverterChargerPage.qml
    pages/loads/AcLoadListPage.qml
    pages/loads/LoadListDelegate.qml
    pages/settings/CanbusProfile.qml
    pages/settings/CanbusServiceFinder.qml
    pages/settings/DvccCommonSettings.qml
    pages/settings/GeneratorCondition.qml
    pages/settings/IpAddressListView.qml
    pages/settings/NetworkSettingsPageModel.qml
    pages/settings/PageCanbusStatus.qml
    pages/settings/PageChargeCurrentLimits.qml
    pages/settings/PageDeviceInfo.qml
    pages/settings/PageGenerator.qml
    pages/settings/PageGeneratorAcLoad.qml
    pages/settings/PageGeneratorConditions.qml
    pages/settings/PageGeneratorRuntimeService.qml
    pages/settings/PageGeneratorTestRun.qml
    pages/settings/PageGps.qml
    pages/settings/PageHub4Debug.qml
    pages/settings/PageRelayGenerator.qml
    pages/settings/PageSettingsAccessAndSecurity.qml
    pages/settings/PageSettingsAcSystem.qml
    pages/settings/PageSettingsAlarmsAndFeedback.qml
    pages/settings/PageSettingsBatteries.qml
    pages/settings/PageSettingsBatteryMeasurements.qml
    pages/settings/PageSettingsBleSensors.qml
    pages/settings/PageSettingsBluetooth.qml
    pages/settings/PageSettingsCanbus.qml
    pages/settings/PageSettingsCanOpenMotordrive.qml
    pages/settings/PageSettingsCGwacs.qml
    pages/settings/PageSettingsCGwacsOverview.qml
    pages/settings/PageSettingsConnectivity.qml
    pages/settings/PageSettingsDisplayAndAppearance.qml
    pages/settings/PageSettingsDisplayBrief.qml
    pages/settings/PageSettingsDisplayMinMax.qml
    pages/settings/PageSettingsDisplayStartPage.qml
    pages/settings/PageSettingsDisplayUnits.qml
    pages/settings/PageSettingsDocumentation.qml
    pages/settings/PageSettingsDvcc.qml
    pages/settings/PageSettingsDynamicEss.qml
    pages/settings/PageSettingsEthernet.qml
    pages/settings/PageSettingsFirmware.qml
    pages/settings/PageSettingsFirmwareOffline.qml
    pages/settings/PageSettingsFirmwareOnline.qml
    pages/settings/PageSettingsFronius.qml
    pages/settings/PageSettingsFroniusInverter.qml
    pages/settings/PageSettingsFroniusInverters.qml
    pages/settings/PageSettingsFroniusSetIpAddresses.qml
    pages/settings/PageSettingsFroniusShowIpAddresses.qml
    pages/settings/PageSettingsGeneral.qml
    pages/settings/PageSettingsGenerator.qml
    pages/settings/PageSettingsGsm.qml
    pages/settings/PageSettingsHub4.qml
    pages/settings/PageSettingsHub4Feedin.qml
    pages/settings/PageSettingsHub4Peakshaving.qml
    pages/settings/PageSettingsIntegrations.qml
    pages/settings/PageSettingsLarge.qml
    pages/settings/PageSettingsLogger.qml
    pages/settings/PageSettingsModbus.qml
    pages/settings/PageSettingsModbusAddDevice.qml
    pages/settings/PageSettingsModbusDevices.qml
    pages/settings/PageSettingsModbusDiscovered.qml
    pages/settings/PageSettingsModbusTcp.qml
    pages/settings/PageSettingsModbusTcpServices.qml
    pages/settings/PageSettingsNodeRed.qml
    pages/settings/PageSettingsRelay.qml
    pages/settings/PageSettingsRelayTempSensors.qml
    pages/settings/PageSettingsRootfsSelect.qml
    pages/settings/PageSettingsRvcDevice.qml
    pages/settings/PageSettingsRvcDeviceConfiguration.qml
    pages/settings/PageSettingsRvcDevices.qml
    pages/settings/PageSettingsShelly.qml
    pages/settings/PageSettingsSignalK.qml
    pages/settings/PageSettingsSupportStatus.qml
    pages/settings/PageSettingsSystem.qml
    pages/settings/PageSettingsSystemStatus.qml
    pages/settings/PageSettingsTankPump.qml
    pages/settings/PageSettingsTcpIp.qml
    pages/settings/PageSettingsVecanDevice.qml
    pages/settings/PageSettingsVecanDevices.qml
    pages/settings/PageSettingsWifi.qml
    pages/settings/PageTzInfo.qml
    pages/settings/PageVrmDeviceInstances.qml
    pages/settings/debug/HubData.qml
    pages/settings/debug/PageDebug.qml
    pages/settings/debug/PageDebugVeQItems.qml
    pages/settings/debug/PagePowerDebug.qml
    pages/settings/debug/PageSettingsDemo.qml
    pages/settings/debug/PageSystemData.qml
    pages/settings/devicelist/DeviceListPage.qml
    pages/settings/devicelist/PageAcCharger.qml
    pages/settings/devicelist/PageDigitalInput.qml
    pages/settings/devicelist/PageGenset.qml
    pages/settings/devicelist/PageMeteo.qml
    pages/settings/devicelist/PageMeteoSettings.qml
    pages/settings/devicelist/PageMotorDrive.qml
    pages/settings/devicelist/PageSwitch.qml
    pages/settings/devicelist/PageUnsupportedDevice.qml
    pages/settings/devicelist/battery/BatteryDetails.qml
    pages/settings/devicelist/battery/BatteryHistory.qml
    pages/settings/devicelist/battery/BatterySettingsAlarmModel.qml
    pages/settings/devicelist/battery/BatterySettingsRelayModel.qml
    pages/settings/devicelist/battery/FuseInfo.qml
    pages/settings/devicelist/battery/Page48TlDiagnostics.qml
    pages/settings/devicelist/battery/PageBattery.qml
    pages/settings/devicelist/battery/PageBatteryAlarms.qml
    pages/settings/devicelist/battery/PageBatteryDetails.qml
    pages/settings/devicelist/battery/PageBatteryHistory.qml
    pages/settings/devicelist/battery/PageBatteryModuleAlarms.qml
    pages/settings/devicelist/battery/PageBatteryParameters.qml
    pages/settings/devicelist/battery/PageBatterySettings.qml
    pages/settings/devicelist/battery/PageBatterySettingsBattery.qml
    pages/settings/devicelist/battery/PageLynxDistributorList.qml
    pages/settings/devicelist/battery/PageLynxIonDiagnostics.qml
    pages/settings/devicelist/battery/PageLynxIonIo.qml
    pages/settings/devicelist/battery/PageLynxIonSystem.qml
    pages/settings/devicelist/dc-in/DcHistorySettingsColumn.qml
    pages/settings/devicelist/dc-in/ListCycleHistoryItem.qml
    pages/settings/devicelist/dc-in/DcBmsSettingsPage.qml
    pages/settings/devicelist/dc-in/PageAlternator.qml
    pages/settings/devicelist/dc-in/PageAlternatorModel.qml
    pages/settings/devicelist/dc-in/PageDcDcConverter.qml
    pages/settings/devicelist/dc-in/PageDcMeter.qml
    pages/settings/devicelist/dc-in/PageDcMeterModel.qml
    pages/settings/devicelist/dc-in/PageDcMeterAlarms.qml
    pages/settings/devicelist/dc-in/PageDcMeterHistory.qml
    pages/settings/devicelist/delegates/AcInDeviceListDelegate.qml
    pages/settings/devicelist/delegates/DcDeviceListDelegate.qml
    pages/settings/devicelist/delegates/DeviceListDelegate_acload.qml
    pages/settings/devicelist/delegates/DeviceListDelegate_acsystem.qml
    pages/settings/devicelist/delegates/DeviceListDelegate_alternator.qml
    pages/settings/devicelist/delegates/DeviceListDelegate_battery.qml
    pages/settings/devicelist/delegates/DeviceListDelegate_charger.qml
    pages/settings/devicelist/delegates/DeviceListDelegate_dcdc.qml
    pages/settings/devicelist/delegates/DeviceListDelegate_dcgenset.qml
    pages/settings/devicelist/delegates/DeviceListDelegate_dcload.qml
    pages/settings/devicelist/delegates/DeviceListDelegate_dcsource.qml
    pages/settings/devicelist/delegates/DeviceListDelegate_dcsystem.qml
    pages/settings/devicelist/delegates/DeviceListDelegate_digitalinput.qml
    pages/settings/devicelist/delegates/DeviceListDelegate_evcharger.qml
    pages/settings/devicelist/delegates/DeviceListDelegate_fuelcell.qml
    pages/settings/devicelist/delegates/DeviceListDelegate_genset.qml
    pages/settings/devicelist/delegates/DeviceListDelegate_gps.qml
    pages/settings/devicelist/delegates/DeviceListDelegate_grid.qml
    pages/settings/devicelist/delegates/DeviceListDelegate_heatpump.qml
    pages/settings/devicelist/delegates/DeviceListDelegate_inverter.qml
    pages/settings/devicelist/delegates/DeviceListDelegate_meteo.qml
    pages/settings/devicelist/delegates/DeviceListDelegate_motordrive.qml
    pages/settings/devicelist/delegates/DeviceListDelegate_multi.qml
    pages/settings/devicelist/delegates/DeviceListDelegate_pulsemeter.qml
    pages/settings/devicelist/delegates/DeviceListDelegate_pvinverter.qml
    pages/settings/devicelist/delegates/DeviceListDelegate_solarcharger.qml
    pages/settings/devicelist/delegates/DeviceListDelegate_switch.qml
    pages/settings/devicelist/delegates/DeviceListDelegate_tank.qml
    pages/settings/devicelist/delegates/DeviceListDelegate_temperature.qml
    pages/settings/devicelist/delegates/DeviceListDelegate_unsupported.qml
    pages/settings/devicelist/delegates/DeviceListDelegate_vebus.qml
    pages/settings/devicelist/delegates/DisconnectedDeviceListDelegate.qml
    pages/settings/devicelist/delegates/GensetDeviceListDelegate.qml
    pages/settings/devicelist/inverter/PageInverter.qml
    pages/settings/devicelist/inverter/PageSolarStats.qml
    pages/settings/devicelist/rs/PageMultiRs.qml
    pages/settings/devicelist/rs/PageRsAlarms.qml
    pages/settings/devicelist/rs/PageRsAlarmSettings.qml
    pages/settings/devicelist/rs/PageRsSystem.qml
    pages/settings/devicelist/rs/PageRsSystemAlarms.qml
    pages/settings/devicelist/rs/PageRsSystemDevices.qml
    pages/settings/devicelist/rs/PageRsSystemEss.qml
    pages/settings/devicelist/tank/PageTankAlarm.qml
    pages/settings/devicelist/tank/PageTankSensor.qml
    pages/settings/devicelist/tank/PageTankSetup.qml
    pages/settings/devicelist/tank/PageTankShape.qml
    pages/settings/devicelist/ac-in/PageAcIn.qml
    pages/settings/devicelist/ac-in/PageAcInSetup.qml
    pages/settings/devicelist/ac-in/PageAcInModel.qml
    pages/settings/devicelist/ac-in/PageSmappeeCTList.qml
    pages/settings/devicelist/ac-in/PageSmappeeCTSetup.qml
    pages/settings/devicelist/ac-in/PageSmappeeDeviceList.qml
    pages/settings/devicelist/pulsemeter/PagePulseCounter.qml
    pages/settings/devicelist/pulsemeter/PagePulseCounterSetup.qml
    pages/settings/devicelist/switchable-outputs/PageSwitchableOutput.qml
    pages/settings/devicelist/switchable-outputs/SwitchableOutputListDelegate.qml
    pages/settings/devicelist/temperature/PageTemperatureSensor.qml
    pages/settings/devicelist/temperature/PageTemperatureSensorSetup.qml
    pages/settings/tz/TzAfricaData.qml
    pages/settings/tz/TzAmericaData.qml
    pages/settings/tz/TzAntarcticaData.qml
    pages/settings/tz/TzArcticData.qml
    pages/settings/tz/TzAsiaData.qml
    pages/settings/tz/TzAtlanticData.qml
    pages/settings/tz/TzAustraliaData.qml
    pages/settings/tz/TzEtcData.qml
    pages/settings/tz/TzEuropeData.qml
    pages/settings/tz/TzIndianData.qml
    pages/settings/tz/TzPacificData.qml
    pages/battery/BatteryListPage.qml
    pages/solar/PageSolarCharger.qml
    pages/solar/PageSolarParallelOperation.qml
    pages/solar/PvInverterPage.qml
    pages/solar/SolarDevicePage.qml
    pages/solar/SolarHistoryPage.qml
    pages/solar/SolarInputListPage.qml
    pages/vebusdevice/PageAcSensor.qml
    pages/vebusdevice/PageAcSensors.qml
    pages/vebusdevice/PageMicrogrid.qml
    pages/vebusdevice/PageVeBusAdvanced.qml
    pages/vebusdevice/PageVeBusAlarms.qml
    pages/vebusdevice/PageVeBusAlarmSettings.qml
    pages/vebusdevice/PageVeBusBms.qml
    pages/vebusdevice/PageVeBusDebug.qml
    pages/vebusdevice/PageVeBusError11Device.qml
    pages/vebusdevice/PageVeBusError11Menu.qml
    pages/vebusdevice/PageVeBusError11View.qml
    pages/vebusdevice/PageVeBusKwhCounters.qml
    pages/vebusdevice/PageVeBusSerialNumbers.qml
    pages/vebusdevice/PageVeBusBackupRestore.qml
    pages/vebusdevice/PVCFListQuantityGroup.qml
    pages/vebusdevice/VeBusAcSensorModel.qml
    pages/vebusdevice/PageVeBus.qml
    pages/vebusdevice/VeBusAlarm.qml
    pages/vebusdevice/VeBusDeviceAlarmGroup.qml
    pages/vebusdevice/VeBusDeviceAlarmSettingsModel.qml
    pages/vebusdevice/VeBusDeviceAlarmStatusModel.qml
    pages/vebusdevice/VeBusDeviceInfoModel.qml
    pages/vebusdevice/VeBusDeviceKwhCountersModel.qml
    pages/welcome/WelcomePage.qml
    pages/welcome/WelcomeView.qml
)

list(APPEND VictronVenusOS_CPP_SOURCES
    src/alldevicesmodel.h
    src/alldevicesmodel.cpp
    src/allservicesmodel.h
    src/allservicesmodel.cpp
    src/aggregatedevicemodel.h
    src/aggregatedevicemodel.cpp
    src/aggregatetankmodel.h
    src/aggregatetankmodel.cpp
    src/visibleitemmodel.h
    src/visibleitemmodel.cpp
    src/baseautotoggleswitch.h
    src/baseautotoggleswitch.cpp
    src/basedevice.h
    src/basedevice.cpp
    src/basedevicemodel.h
    src/basedevicemodel.cpp
    src/basetankdevice.h
    src/basetankdevice.cpp
    src/basetankdevicemodel.h
    src/basetankdevicemodel.cpp
    src/colordimmerdata.h
    src/colordimmerdata.cpp
    src/dcmeterdevicemodel.h
    src/dcmeterdevicemodel.cpp
    src/device.h
    src/device.cpp
    src/evchargerdevicemodel.h
    src/evchargerdevicemodel.cpp
    src/evchargerstatusmodel.h
    src/evchargerstatusmodel.cpp
    src/filtereddevicemodel.h
    src/filtereddevicemodel.cpp
    src/filteredservicemodel.h
    src/filteredservicemodel.cpp
    src/guiplugins.h
    src/guiplugins.cpp
    src/runtimedevicemodel.h
    src/runtimedevicemodel.cpp
    src/theme.h
    src/theme.cpp
    src/themeobjects.h
    src/backendconnection.h
    src/backendconnection.cpp
    src/language.h
    src/language.cpp
    src/enums.h
    src/enums.cpp
    src/fastutils.h
    src/fastutils.cpp
    src/notificationmodel.h
    src/notificationmodel.cpp
    src/notificationsortfilterproxymodel.h
    src/notificationsortfilterproxymodel.cpp
    src/clocktime.h
    src/clocktime.cpp
    src/cpuinfo.h
    src/cpuinfo.cpp
    src/frameratemodel.h
    src/frameratemodel.cpp
    src/keyeventfilter.h
    src/keyeventfilter.cpp
    src/keynavigationhighlight.cpp
    src/keynavigationhighlight.h
    src/keynavigationhighlighthelper.h
    src/keynavigationhighlighthelper.cpp
    src/mockanimators.h
    src/mockmanager.h
    src/mockmanager.cpp
    src/phasemodel.h
    src/phasemodel.cpp
    src/productinfo.h
    src/qmlobject.h
    src/qmlobject.cpp
    src/quantityinfo.h
    src/quantityinfo.cpp
    src/quantityobject.h
    src/quantityobject.cpp
    src/quantityobjectmodel.h
    src/quantityobjectmodel.cpp
    src/qrangemodel_p.h
    src/qrangemodel.h
    src/qrangemodel.cpp
    src/units.h
    src/units.cpp
    src/screenblanker.h
    src/screenblanker.cpp
    src/solarinput.h
    src/solarinput.cpp
    src/solarinputmodel.h
    src/solarinputmodel.cpp
    src/solaryieldmodel.h
    src/solaryieldmodel.cpp
    src/switchableoutput.h
    src/switchableoutput.cpp
    src/switchableoutputmodel.h
    src/switchableoutputmodel.cpp
    src/switchableoutputgroupmodel.h
    src/switchableoutputgroupmodel.cpp
    src/widgetconnectorpathupdater.h
    src/widgetconnectorpathupdater.cpp
)

if (VENUS_GX_BUILD)
    list(APPEND VictronVenusOS_CPP_SOURCES
        src/urlinterceptor.h
        src/urlinterceptor.cpp)
endif()

set(VictronVenusOS_RESOURCES
    fonts/Roboto-Regular.ttf
    images/acloads.svg
    images/alternator.svg
    images/breadcrumb_lhs.svg
    images/breadcrumb_rhs.svg
    images/icon_battery_24.svg
    images/icon_battery_charging_24.svg
    images/icon_battery_discharging_24.svg
    images/icon_connectivity_32.png
    images/icon_debug_32.png
    images/icon_devices_32.png
    images/icon_general_32.png
    images/icon_integration_32.png
    images/icon_smartswitch_off_32.svg
    images/icon_smartswitch_on_32.svg
    images/icon_system_32.png
    images/icon_vrm_32.png
    images/brief.svg
    images/cloud.svg
    images/color_wheel_rgb.png
    images/color_wheel_temperature.png
    images/consumption.svg
    images/dcloads.svg
    images/dot.svg
    images/dropdown.svg
    images/electron.svg
    images/electron_arrow.svg
    images/ess.svg
    images/freshWater.svg
    images/key_navigation_highlight_dark.svg
    images/key_navigation_highlight_light.svg
    images/icon_black_water_24.svg
    images/icon_charging_generator.svg
    images/icon_charging_grid.svg
    images/icon_charging_renewables.svg
    images/icon_charging_shore.svg
    images/icon_CL_24.svg
    images/icon_edit_32.svg
    images/icon_fresh_water_24.svg
    images/icon_raw_water_24.svg
    images/icon_waste_water_24.svg
    images/icon_livewell_24.svg
    images/icon_fuel_24.svg
    images/icon_from_grid.svg
    images/icon_oil_24.svg
    images/icon_hydraulic_oil_24.svg
    images/icon_lng_24.svg
    images/icon_lpg_24.svg
    images/icon_open_link_32.svg
    images/icon_to_grid.svg
    images/fueltank.svg
    images/gauge_intro_5_matte_black.gif
    images/gauge_intro_5_matte_white.gif
    images/gauge_intro_7_matte_black.gif
    images/gauge_intro_7_matte_white.gif
    images/generator.svg
    images/grid.svg
    images/icon_simlocked_32.svg
    images/icon_warning_24.svg
    images/icon_alarm_32.svg
    images/icon_alarm_48.svg
    images/icon_alarm_snooze_24.svg
    images/icon_autostart_24.svg
    images/icon_arrow_32.svg
    images/icon_back_32.svg
    images/icon_charging_station_24.svg
    images/icon_checkmark_48.svg
    images/icon_controls_off_32.svg
    images/icon_controls_on_32.svg
    images/icon_dc_24.svg
    images/icon_humidity_32.svg
    images/icon_input_24.svg
    images/icon_manualstart_24.svg
    images/icon_manualstart_timer_24.svg
    images/icon_minus.svg
    images/icon_plus.svg
    images/icon_plus_32.svg
    images/icon_refresh_32.svg
    images/icon_sidepanel_off_32.svg
    images/icon_sidepanel_on_32.svg
    images/icon_screen_sleep_32.svg
    images/icon_switch_24.svg
    images/icon_temp_32.svg
    images/information.svg
    images/inverter.svg
    images/inverter_charger.svg
    images/levels.svg
    images/notifications.svg
    images/notifications_subtract.svg
    images/overview.svg
    images/rain.svg
    images/scatteredcloud.svg
    images/settings.svg
    images/shore.svg
    images/slider_background_light.svg
    images/slider_background_dark.svg
    images/solaryield.svg
    images/spinbox_arrow_up.svg
    images/splash-logo-icon.svg
    images/splash-logo-text.svg
    images/sunny.svg
    images/switch_indicator.png
    images/switches.svg
    images/icon_warning_32.svg
    images/icon_checkmark_32.svg
    images/icon_close_32.svg
    images/icon_info_32.svg
    images/icon_info_48.svg
    images/icon_WiFi_1_32.svg
    images/icon_WiFi_2_32.svg
    images/icon_WiFi_3_32.svg
    images/icon_WiFi_4_32.svg
    images/icon_WiFi_noconnection_32.svg
    images/welcome-brief.png
    images/welcome-controls.png
    images/welcome-dark.png
    images/welcome-landing.png
    images/welcome-more.png
    images/welcome-overview.png
    images/welcome-qrCode.png
    images/welcome-qrCode-light.png
    images/welcome-units.png
    images/widget_connector_nub_horizontal.svg
    images/widget_connector_nub_vertical.svg
    images/wind.svg
    themes/animation/Animation.json
    themes/color/ColorDesign.json
    themes/color/Dark.json
    themes/color/Light.json
    themes/geometry/FiveInch.json
    themes/geometry/SevenInch.json
    themes/typography/FiveInch.json
    themes/typography/SevenInch.json
    themes/typography/TypographyDesign.json
)
