set(VictronMock_QML_MODULE_SOURCES
    data/mock/BatteriesImpl.qml
    data/mock/DevicesImpl.qml
    data/mock/EvChargersImpl.qml
    data/mock/GeneratorsImpl.qml
    data/mock/InverterChargersImpl.qml
    data/mock/MiscServicesImpl.qml
    data/mock/MockSetup.qml
    data/mock/MockShortcuts.qml
    data/mock/MotorDrivesImpl.qml
    data/mock/MockNotification.qml
    data/mock/NotificationsImpl.qml
    data/mock/SolarInputsImpl.qml
    data/mock/SystemAcImpl.qml
    data/mock/SystemDcImpl.qml
    data/mock/TanksImpl.qml
    data/mock/TemperaturesImpl.qml
    data/mock/page-conf/BoatPageConfig.qml
    data/mock/page-conf/BriefAndOverviewPageConfig.qml
    data/mock/page-conf/LevelsPageConfig.qml
)

SET(VictronMock_QML_MODULE_RESOURCES
    data/mock/conf/barebones.json
    data/mock/conf/dc-only.json
    data/mock/conf/maximal.json
    data/mock/conf/multi-rs.json
    data/mock/conf/split-phase.json
    data/mock/conf/switch-pane.json
    data/mock/conf/services/alternator.json
    data/mock/conf/services/dcgenset.json
    data/mock/conf/services/dcload-fridge.json
    data/mock/conf/services/dcsystem1.json
    data/mock/conf/services/dcsystem2.json
    data/mock/conf/services/dse-genset.json
    data/mock/conf/services/digitalinput-alarm.json
    data/mock/conf/services/em-acload.json
    data/mock/conf/services/em-evcharger-input.json
    data/mock/conf/services/em-evcharger-output.json
    data/mock/conf/services/em-genset.json
    data/mock/conf/services/em-grid.json
    data/mock/conf/services/em-heatpump-input.json
    data/mock/conf/services/em-heatpump-output.json
    data/mock/conf/services/em-pvinverter.json
    data/mock/conf/services/ess.json
    data/mock/conf/services/ev.json
    data/mock/conf/services/evcharger1.json
    data/mock/conf/services/fronius.json
    data/mock/conf/services/generator.json
    data/mock/conf/services/gioextender.json
    data/mock/conf/services/gps.json
    data/mock/conf/services/inverter-rs.json
    data/mock/conf/services/lynxbms.json
    data/mock/conf/services/lynxparallel.json
    data/mock/conf/services/meteo-solarsense.json
    data/mock/conf/services/modem.json
    data/mock/conf/services/motordrive.json
    data/mock/conf/services/mppt1.json
    data/mock/conf/services/mppt2.json
    data/mock/conf/services/multiplus-split-phase.json
    data/mock/conf/services/multirs-smart.json
    data/mock/conf/services/network-bluetooth.json
    data/mock/conf/services/network-wifi-and-ethernet.json
    data/mock/conf/services/notifications-alarm.json
    data/mock/conf/services/notifications-no-alarm.json
    data/mock/conf/services/opportunityloads.json
    data/mock/conf/services/orionxs-alternator.json
    data/mock/conf/services/orionxs-dcdc.json
    data/mock/conf/services/phoenix-smart-charger.json
    data/mock/conf/services/pulsemeter.json
    data/mock/conf/services/pump.json
    data/mock/conf/services/pvinverter.json
    data/mock/conf/services/pylontech.json
    data/mock/conf/services/quattro-3phase-grid-genset.json
    data/mock/conf/services/relays-temperature-and-manual.json
    data/mock/conf/services/ruuvi-fridge.json
    data/mock/conf/services/ruuvi-salon.json
    data/mock/conf/services/shelly.json
    data/mock/conf/services/skylla-charger.json
    data/mock/conf/services/smartshunt-battery.json
    data/mock/conf/services/smartshunt-dcsource.json
    data/mock/conf/services/smartswitch.json
    data/mock/conf/services/switch-controls-tester.json
    data/mock/conf/services/tank-blackwater-error-state.json
    data/mock/conf/services/tank-fuel1.json
    data/mock/conf/services/tank-fuel2.json
    data/mock/conf/services/tank-fuel3.json
    data/mock/conf/services/tank-greywater.json
    data/mock/conf/services/tank-lpg.json
    data/mock/conf/services/tank-water1.json
    data/mock/conf/services/tank-water2.json
    data/mock/conf/services/tank-water3.json
    data/mock/conf/services/tank-water4.json
    data/mock/conf/services/temperature-freezer.json
    data/mock/conf/services/temperature-watertank.json
    data/mock/conf/services/unsupported.json
    data/mock/conf/services/wind.json
    data/mock/conf/setup-common.json
    data/mock/conf/setup-essential-loads.json
)
